language : bash
env:
    global:
      - HUB_PROTOCOL=https
      #GITHUB_TOKEN
      - secure: "bPxk9oRsLzwfqutnD/CELhx6vLB7mds9hTbc47rGuixlQyKh7tw+YadbL7mURolE5eBcnohKoixnkO2BF3ysxwKipsdo8tm76RsfMMlAbWQUHjcQuBgn4PYJlVQOM1UiBQMV5m6dVSwB3jcROFGq8E74Z9L0mah6CharYoCr6EV8gDP4CBQEcWJ24IMLVnChU71XfyCkLENfzXYYd8jAFDzjg02glfK4O6wGGC+jXRbdDCooHkhnyYI5Dy7BFGMhJNGI5EGf2jF1Ms9tQ0QHITuwgTRfdZsFJ3fuujJOq2iMAJUg3nu4dNfssYxj+4Ors4tARXpftkm1yENtcOPOxyFSObJjmdASkmF8PftvgC5uZsgATFWUeqf6drnUKqIVIHUJDsdwvMlarAmo+evZgFhnVOIL9omk2aJqAcRtQMbM9njKumCDxUxsMRjSvl/4KPHgbiRcyqvws8UbGuR+yq3y7dvkxkk5fzP9AYPg5Q8JDslr7xhqkfoK2uWcgiZwmuf6IcPVj0T9+70MY5LM3ArOSefQEmrjfe11rONv9NKWqBUaDrg/+btwP2E8i0UGmBLc6z3KYZrHJGZ8U5oA4793645fDTWlt7lY6GQ0mby13Kf82XXRU5jWl2T1SuxkGV94PvmYHh5M2jyPBbu/coYmjX96FZuGwnW/tCTDXMM="
branches:
  except:
  - nightly
git:
  quiet: true
before_install:
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - sudo apt-get -qq update
    - sudo apt-get install -y debhelper devscripts fakeroot build-essential po-debconf gh
    - openssl aes-256-cbc -K $encrypted_2155243bff9e_key -iv $encrypted_2155243bff9e_iv -in 077CC9F2.gpg.enc -out 077CC9F2.gpg -d
    - gpg --import 077CC9F2.gpg
install:
    - debuild '-k9D1DC8DD077CC9F2'
deploy:
    - provider: releases
      skip_cleanup: true
      file_glob: true
      file: "../*.deb"
      api_key:
          secure: "c2DC0aM7DsnHJB1l+CQQZb3IczB6l5HuqcOuKkxDt3mUihC8TV21PnZzAtlm6mRT7gPO9zFL+EAXBSToWYe/jcIRPCyPWlcnblXVS2ev0iKV77op2qoMKqUjBu6t7PviXA15JVfS8O+wp4Wq1A4D4Nxsxr9qnqRHkTLruRtLs/B36I89XitDooTgM93EkTFUBCCBwbQzsuVAqzIpnW3Mmy9YPnbbh73XnyMmZxV1D3HHClCJiP0DjzRqL4OZ37+Har4b/5LrL/Onj5b39GkzX9bnlips+MFv5w4uOf5Z63/Xvg1aPdGcHWpBydWmy3Yfq55qMu13QqgiCf9wD18kLfD2YFu0xXmg3v7cERNr1pPMhW22V32Ru56huUGpsoopMJOUgUCpXF+VF1QtlvG8DBthFazwzO7C0CYxeF3Z5w6PwdeVq70WeE3ZoFrKwI/aFSou/UUZ7t51qgN1ZsEjDaB0wJSgvoIX/LRm+qLIeUGxl16oy9fOG5rJo+3aaSTeebejFsXCjLNVivz110p7wRHEtuk/wnYDnV2FBweGGgq4UWHXOqlJ7psgOTTWOE7DnMhmsrMcJ0QJrKyyzPa1vgFBsD+8sr0guGcxc/KvcsNdoKUww7aNYEK34qngKq4liAdjxifrt8Fh0j+qPiiL/FNTAfWQzPFga/YyMQNP9eU="
      on:
          tags: true
    - provider: releases
      skip_cleanup: true
      file_glob: true
      file: "../*.deb"
      tag_name: "nightly"
      prerelease: true
      name: Automatic nightly build by Travis on $(date +'%F %T %Z').
      target_commitish: $TRAVIS_COMMIT
      api_key:
          secure: "c2DC0aM7DsnHJB1l+CQQZb3IczB6l5HuqcOuKkxDt3mUihC8TV21PnZzAtlm6mRT7gPO9zFL+EAXBSToWYe/jcIRPCyPWlcnblXVS2ev0iKV77op2qoMKqUjBu6t7PviXA15JVfS8O+wp4Wq1A4D4Nxsxr9qnqRHkTLruRtLs/B36I89XitDooTgM93EkTFUBCCBwbQzsuVAqzIpnW3Mmy9YPnbbh73XnyMmZxV1D3HHClCJiP0DjzRqL4OZ37+Har4b/5LrL/Onj5b39GkzX9bnlips+MFv5w4uOf5Z63/Xvg1aPdGcHWpBydWmy3Yfq55qMu13QqgiCf9wD18kLfD2YFu0xXmg3v7cERNr1pPMhW22V32Ru56huUGpsoopMJOUgUCpXF+VF1QtlvG8DBthFazwzO7C0CYxeF3Z5w6PwdeVq70WeE3ZoFrKwI/aFSou/UUZ7t51qgN1ZsEjDaB0wJSgvoIX/LRm+qLIeUGxl16oy9fOG5rJo+3aaSTeebejFsXCjLNVivz110p7wRHEtuk/wnYDnV2FBweGGgq4UWHXOqlJ7psgOTTWOE7DnMhmsrMcJ0QJrKyyzPa1vgFBsD+8sr0guGcxc/KvcsNdoKUww7aNYEK34qngKq4liAdjxifrt8Fh0j+qPiiL/FNTAfWQzPFga/YyMQNP9eU="
      on:
          branch: master
before_deploy:
    - >
      if [[ $TRAVIS_BRANCH == "master" ]]; then
        gh release delete nightly -R ${TRAVIS_REPO_SLUG} -y
        git tag -f nightly || true &&
        git remote add gh https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git &&
        git push --delete -f gh nightly || true &&
        git push -f gh nightly || true
      fi
