#! /bin/bash
# postrm script
#

set -e

case "$1" in
	remove|purge)

		echo "Remove template configuration"
		mysql --defaults-file=/etc/alternc/my.cnf -e "
			DELETE FROM domaines_type WHERE name='proxy';
		"
	# Run also specific purge action
	;&

	purge)

		if [ -e /usr/share/debconf/confmodule ]; then
		    # Source debconf library.
		    . /usr/share/debconf/confmodule
		    # Remove my changes to the db.
		    db_purge
		fi
	;;

	upgrade|disappear|failed-upgrade|abort-install|abort-upgrade)

	;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
