#! /bin/bash
# postinst script
#

set -e

case "$1" in
	configure)

		if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
			. /usr/share/apache2/apache2-maintscript-helper
			apache2_has_module proxy_http || apache2_invoke enmod proxy_http 2>/dev/null || exit $?
		fi

		echo "Installing mysql table"
		mysql --defaults-file=/etc/alternc/my.cnf -e "
			INSERT IGNORE INTO domaines_type SET name='proxy', description='Proxy to remote server', target='DOMAIN', entry='%SUB% IN A @@PUBLIC_IP@@', compatibility='txt,defmx,defmx2,mx,mx2', enable='ALL', need_dns=0, has_https_option=0, create_targetdir=0;
			UPDATE sub_domaines SET web_action='UPDATE' WHERE type IN ('proxy');
		"
	;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
